# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LoHYS63etmLm_J8oNlKRXi9MeEO-blLN
"""

import pandas as pd
import numpy as np

df = pd.read_csv('data.csv', sep = ';', engine='python', encoding='utf-8')

print(df.info())
print(df[-3:])

df_copy = df
df_copy['Calories'].fillna('0', inplace=True)
print(df_copy)

df_copy['Date'].fillna('1900/01/01', inplace=True)
print(df_copy)
df_copy['Date'].replace('1900/01/01', np.nan, inplace=True)
df_copy['Date'].replace('20201226', pd.to_datetime('20201226'), inplace=True)
df_copy['Date'] = pd.to_datetime(df_copy['Date'])
df_copy['Date'].fillna(pd.to_datetime('1900/01/01'), inplace=True)

print(df_copy)